### ISSUE TITLE
npm install hangs on extract

### ISSUE THREAD

**Issue by christian-valadez** [RedPillNow/polymerts-to-polymer-decorators#1]
I'm trying to install this project, but npm hangs on extract:

`extract:typescript: timing audit body Completed in 0ms`

Using:
npm version: 6.4.1
node version: v10.12.0

This is a really well-done project, and I would love to be able to use it for my app.

**Comment by keithstric** [comment]
Thanks for trying this out, it's in desperate need of finishing however due to my current workload I just haven't had the time to finish it.

Regarding your npm install issue, it's because I had the [polymerts-models](https://github.com/RedPillNow/polymerts-models) dependency listed as a local resource instead of a repository. So, just committed a change to get that working.

Please be aware this project is nowhere near ready for public consumption, however it should lessen the task of converting elements by hand.
